package:
  name: xz
  version: 5.0.5

source:
  fn:  xz-5.0.5.tar.gz
  url: http://tukaani.org/xz/xz-5.0.5.tar.gz

build:
  number: 2            [osx]

about:
  home: tukaani
  license: Eclipse Public License 1.0
