package:
  name: java-jdk
  version: 8.45.14

# Cannot use source section because of cookies blocking download
#source:
#  fn: jre-8u25-linux-x64.tar.gz
#  url: http://download.oracle.com/otn-pub/java/jdk/8u25-b17/jre-8u25-linux-x64.tar.gz

requirements:
  build:
    - curl # [win]

about:
  home: http://www.java.com/en/
  license: Oracle Binary Code License Agreement for the Java SE Platform Products and JavaFX
