package:
  name: myglib
  version: 2.37.4

source:
  fn: glib-2.37.4.tar.xz
  url: http://ftp.acc.umu.se/pub/GNOME/sources/glib/2.37/glib-2.37.4.tar.xz

build:
  number: 2            [osx]

# the build and runtime requirements. Dependencies of these requirements
# # are included automatically.
# requirements:
#   # Packages required to build the package. python and numpy must be
#     # listed explicitly if they are required.
requirements:
  build:
   - python
   - libffi
   - pkg-config-lite
   - gettext
about:
  home: Glib
  license: Eclipse Public License 1.0
