package:
  name: mylibxml2
  version: 2.8.0

source:
  fn:  libxml2-2.8.0.tar.gz
  url: ftp://xmlsoft.org/libxml2/libxml2-2.8.0.tar.gz

build:
  number: 2            [osx]

requirements:
 build:
  - sigcpp
  - myglib
  - glibmm
  - pkg-config-lite
  
about:
  home: libxmlpp
  license: Eclipse Public License 1.0
