package:
  name: sigcpp
  version: 2.3.1

source:
  fn:  libsigc++-2.3.1.tar.xz
  url:  http://ftp.gnome.org/pub/GNOME/sources/libsigc++/2.3/libsigc++-2.3.1.tar.xz

build:
  number: 2            [osx]


about:
  home: Coin
  license: Eclipse Public License 1.0
