package:
  name: libxmlpp
  version: 2.36.0

source:
  fn: libxml++-2.36.0.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/libxml++/2.36/libxml++-2.36.0.tar.xz

build:
  number: 2            [osx]

requirements:
 build:
  - xz
  - sigcpp
  - myglib # [osx]
  - glibmm
  - pkg-config-lite # [osx]
  - mylibxml2 # [osx]
  - libxml2   # [not osx]
  - libffi # [osx]
  - gettext  # [osx]
about:
  home: libxmlpp
  license: Eclipse Public License 1.0
