package:
  name: coincbc
  version: 2.8.3

source:
  fn: Cbc-2.8.3.tgz
  url: http://www.coin-or.org/download/source/Cbc/Cbc-2.8.3.tgz

build:
  number: 2            [osx]

about:
  home: Coin
  license: Eclipse Public License 1.0
