package:
  name: cyclus-deps
  version: 9999

requirements:
   build:
    - sigcpp
    - myglib
    - glibmm
    - libxmlpp
    - bzip2 
    - coincbc
    - boost
    - hdf5
    - mylibxml2 # [osx]
    - libxml2  #  [linux]
    - myglib   # [osx]  
    - libffi # [osx]
    - gettext # [osx]
    - pkg-config-lite # [osx]
    - cmake
    - python
    - nose
    - pytables

   run:
    - sigcpp
    - myglib
    - glibmm
    - libxmlpp
    - bzip2 
    - coincbc
    - boost
    - hdf5
    - mylibxml2 # [osx]
    - libxml2  #  [linux]
    - myglib   # [osx]  
    - libffi # [osx]
    - gettext # [osx]
    - pkg-config-lite # [osx]
    - cmake
    - python
    - nose
    - pytables

build:
  string: 0

about:
  home: Cyclus
  license: BSD Clause 3
