package:
  name: gettext
  version: 0.18.3

source:
  fn:  gettext-0.18.3.tar.gz
  url: http://ftp.gnu.org/gnu/gettext/gettext-0.18.3.tar.gz

build:
  number: 2            [osx]

requirements:
 build:
  - xz
  - libffi
about:
  home: gettext
  license: Eclipse Public License 1.0
