package:
  name: cyclist
  version: 0.9.3

source:
  # keep these commented lines for batlab
  #fn: 0.9.3.tar.gz
  #url: https://github.com/cyclus/cyclist2/archive/0.9.3.tar.gz
  git_url: http://github.com/cyclus/cyclist2.git
  git_tag: 0.9.3

requirements:
   build:
    - java-jdk
    - ant
   run:
    - java-jre
    - cycamore # [unix]
    - launcher

# If the app key makes this appear in the launcher.
app:
  # The command that is called to launch the app
  entry: cyclist
  #icon: icon64x64.png
  summary: Cyclist is a visual interface companion for the Cyclus project.

about:
  home: http://fuelcycle.org
  license: BSD 3-Clause
  summary: Cyclist is a visual interface companion for the Cyclus project.
